spring:
  application:
    name: lol-tracker
  datasource:
    url: jdbc:postgresql://localhost:5432/lol-tracker
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true

riot:
  api-key: ${API_KEY}

logging:
  level:
    com.example.loltracker: debug
    org.springframework.web.client: debug

